set("RE2_BUILD_TESTING" "OFF" CACHE INTERNAL "")
set("CMAKE_POSITION_INDEPENDENT_CODE" "ON" CACHE INTERNAL "")
set("CMAKE_CXX_STANDARD" "20" CACHE INTERNAL "")
set("CMAKE_CXX_STANDARD_REQUIRED" "ON" CACHE INTERNAL "")
